GET http://localhost:2000/users HTTP/1.1
Content-Type:  application/json

###
POST http://localhost:2000/products HTTP/1.1
Content-Type:  application/json

{"products":[{
    "image": "zurag shu8uu",
    "name": "yunjee",
    "stock": 9,
    "price": 2200,
    "sale": 10,
    "id": "10284780909dacvaSDVGAWR;KGA'EWRBN0"
  },{
    "image": "bas l zurag",
    "name": "ukaa",
    "stock": 9,
    "price": 2200,
    "sale": 10,
    "id": "10284780909dacvaSDVGAWR;KGA'EWRBN0"
  }]}

###
DELETE  http://localhost:2000/products HTTP/1.1
Content-Type:  application/json

{"image": "zurag shu8uu"}

###
PUT http://localhost:2000/products HTTP/1.1
Content-Type:  application/json

{"id": "102847809090"}